// <auto-generated />
using System;
using E_commerceClassLibrary.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_commerceClassLibrary.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    [Migration("20241205174234_addImageToProduct")]
    partial class addImageToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Line Art"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dalle"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pants"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hoodie"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Underwear"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Red"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Green"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Blue"
                        },
                        new
                        {
                            Id = 4,
                            Name = "White"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ColorId");

                    b.HasIndex("SizeId");

                    b.HasIndex("Name", "BrandId", "ColorId", "SizeId")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            ColorId = 1,
                            ImagePath = "images/ShirtRed.png",
                            Name = "Line Art Shirt",
                            Price = 1499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            ColorId = 2,
                            ImagePath = "images/ShirtGreen.png",
                            Name = "Line Art Shirt",
                            Price = 1499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            ColorId = 3,
                            ImagePath = "images/ShirtBlue.png",
                            Name = "Line Art Shirt",
                            Price = 1499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 2,
                            ColorId = 1,
                            ImagePath = "images/PantsRed.png",
                            Name = "Line Art Pants",
                            Price = 1099.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 2,
                            ColorId = 2,
                            ImagePath = "images/PantsGreen.png",
                            Name = "Line Art Pants",
                            Price = 1099.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 1,
                            CategoryId = 2,
                            ColorId = 3,
                            ImagePath = "images/PantsBlue.png",
                            Name = "Line Art Pants",
                            Price = 1099.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CategoryId = 3,
                            ColorId = 1,
                            ImagePath = "images/JacketRed.png",
                            Name = "Line Art Jacket",
                            Price = 2499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            CategoryId = 3,
                            ColorId = 2,
                            ImagePath = "images/JacketGreen.png",
                            Name = "Line Art Jacket",
                            Price = 2499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            CategoryId = 3,
                            ColorId = 3,
                            ImagePath = "images/JacketBlue.png",
                            Name = "Line Art Jacket",
                            Price = 2499.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            CategoryId = 4,
                            ColorId = 1,
                            ImagePath = "images/HoodieRed.png",
                            Name = "Line Art Hoodie",
                            Price = 1899.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            CategoryId = 4,
                            ColorId = 2,
                            ImagePath = "images/HoodieGreen.png",
                            Name = "Line Art Hoodie",
                            Price = 1899.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            CategoryId = 4,
                            ColorId = 3,
                            ImagePath = "images/HoodieBlue.png",
                            Name = "Line Art Hoodie",
                            Price = 1899.99m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 2,
                            CategoryId = 4,
                            ColorId = 4,
                            ImagePath = "images/DallHoodie.webp",
                            Name = "Dalle Hoodie",
                            Price = 777m,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 2,
                            CategoryId = 4,
                            ColorId = 4,
                            ImagePath = "images/DallHoodie.webp",
                            Name = "Dalle Hoodie",
                            Price = 777m,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 2,
                            CategoryId = 4,
                            ColorId = 4,
                            ImagePath = "images/DallHoodie.webp",
                            Name = "Dalle Hoodie",
                            Price = 777m,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 2,
                            CategoryId = 4,
                            ColorId = 4,
                            ImagePath = "images/DallHoodie.webp",
                            Name = "Dalle Hoodie",
                            Price = 777m,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 2,
                            CategoryId = 3,
                            ColorId = 4,
                            ImagePath = "images/DallJacket.webp",
                            Name = "Dalle Jacket",
                            Price = 777m,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 2,
                            CategoryId = 2,
                            ColorId = 4,
                            ImagePath = "images/DallPants.webp",
                            Name = "Dalle Pants",
                            Price = 777m,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 2,
                            CategoryId = 1,
                            ColorId = 4,
                            ImagePath = "images/DallShirt.webp",
                            Name = "Dalle Shirt",
                            Price = 777m,
                            SizeId = 2
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "S"
                        },
                        new
                        {
                            Id = 2,
                            Name = "M"
                        },
                        new
                        {
                            Id = 3,
                            Name = "L"
                        },
                        new
                        {
                            Id = 4,
                            Name = "XL"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 6,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 7,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 8,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 9,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 10,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 11,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 12,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 13,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 14,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 15,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 16,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 17,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 18,
                            Quantity = 100
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 19,
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("OrderId", "ProductId")
                        .IsUnique()
                        .HasFilter("[OrderId] IS NOT NULL");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Stockholm",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "0123456789",
                            Street = "Main Street 1"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2024, 12, 5, 18, 42, 33, 990, DateTimeKind.Local).AddTicks(4123),
                            OrderStatus = "Pending",
                            TotalPrice = 1499.99m
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.OrderStaffAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StaffId");

                    b.ToTable("OrderStaffAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            StaffId = 1
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "anna.smith@example.com",
                            FirstName = "Anna",
                            LastName = "Smith",
                            Phone = "9876543210"
                        });
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Product", b =>
                {
                    b.HasOne("E_commerceClassLibrary.Models.Production.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerceClassLibrary.Models.Production.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerceClassLibrary.Models.Production.Color", "Color")
                        .WithMany("Products")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerceClassLibrary.Models.Production.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Stock", b =>
                {
                    b.HasOne("E_commerceClassLibrary.Models.Production.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("E_commerceClassLibrary.Models.Production.Stock", "ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.CartItem", b =>
                {
                    b.HasOne("E_commerceClassLibrary.Models.Sales.Order", "Order")
                        .WithMany("CartItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("E_commerceClassLibrary.Models.Production.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Order", b =>
                {
                    b.HasOne("E_commerceClassLibrary.Models.Sales.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.OrderStaffAssignment", b =>
                {
                    b.HasOne("E_commerceClassLibrary.Models.Sales.Order", "Order")
                        .WithMany("OrderStaffAssignments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_commerceClassLibrary.Models.Sales.Staff", "Staff")
                        .WithMany("OrderStaffAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Color", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Product", b =>
                {
                    b.Navigation("Stock");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Production.Size", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Order", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderStaffAssignments");
                });

            modelBuilder.Entity("E_commerceClassLibrary.Models.Sales.Staff", b =>
                {
                    b.Navigation("OrderStaffAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
